//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB01.CUKCUK.NVTHUY.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB01.CUKCUK.NVTHUY.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn đã tồn tại trong hệ thống.
        /// </summary>
        public static string DuplicateFoodCode {
            get {
                return ResourceManager.GetString("DuplicateFoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA.
        /// </summary>
        public static string ErrorException {
            get {
                return ResourceManager.GetString("ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối database.
        /// </summary>
        public static string ExceptionConnection {
            get {
                return ResourceManager.GetString("ExceptionConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dữ liệu không thành công.
        /// </summary>
        public static string ExceptionDelete {
            get {
                return ResourceManager.GetString("ExceptionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất file Excel không thành công.
        /// </summary>
        public static string ExceptionExcel {
            get {
                return ResourceManager.GetString("ExceptionExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc dữ liệu không thành công.
        /// </summary>
        public static string ExceptionFilter {
            get {
                return ResourceManager.GetString("ExceptionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dữ liệu không thành công.
        /// </summary>
        public static string ExceptionInsert {
            get {
                return ResourceManager.GetString("ExceptionInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy mã mới không thành công.
        /// </summary>
        public static string ExceptionNewCode {
            get {
                return ResourceManager.GetString("ExceptionNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa dữ liệu không thành công.
        /// </summary>
        public static string ExceptionUpdate {
            get {
                return ResourceManager.GetString("ExceptionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào là null.
        /// </summary>
        public static string InputNullData {
            get {
                return ResourceManager.GetString("InputNullData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu đầu vào không hợp lệ.
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian vượt quá ngày hiện tại.
        /// </summary>
        public static string InvalidDateOfBirth {
            get {
                return ResourceManager.GetString("InvalidDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã món ăn không được để trống.
        /// </summary>
        public static string InvalidFoodCode {
            get {
                return ResourceManager.GetString("InvalidFoodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên món ăn không được để trống.
        /// </summary>
        public static string InvalidFoodName {
            get {
                return ResourceManager.GetString("InvalidFoodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá bán không được để trống.
        /// </summary>
        public static string InvalidFoodPrice {
            get {
                return ResourceManager.GetString("InvalidFoodPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được để trống.
        /// </summary>
        public static string InvalidFoodUnit {
            get {
                return ResourceManager.GetString("InvalidFoodUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian vượt quá ngày hiện tại.
        /// </summary>
        public static string InvalidIdentityDate {
            get {
                return ResourceManager.GetString("InvalidIdentityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trả về là null.
        /// </summary>
        public static string NullData {
            get {
                return ResourceManager.GetString("NullData", resourceCulture);
            }
        }
    }
}
